CREATE TABLE IF NOT EXISTS broker(
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,   
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 





/*
insert INTO broker(nombre) VALUES 
('ALE TOLENTINO','2.5'),
('ANGELICA KURI','3'),
('ARMANDO GUERRERO','4'),
('AVIS MATIAS','1.2'),
('BROKER KUME','1.8'),
('CANDY','1.8'),
('CASSANDRA','3'),
('CRISTIAN GOMEZ','4'),
('CUÑADO HÉCTOR','1.2'),
('DESPACHO DE MONTERREY','2.5'),
('EFECTIVO A KUME','3'),
('EMMANUEL','4'),
('FRANCISCO GUZMAN','1.2'),
('GILDA','1.8'),
('GUILLERMO y NOE','1.8'),
('ING. STEFANO JUÁREZ','3'),
('JOHN','4'),
('JUAN ORTÍZ','1.8'),
('KIKE CORREA','1.8'),
('LUIGI','3'),
('MAICOL','4'),
('MARÍA JOSÉ PALMA','3'),
('MIGUEL','4'),
('NIDIA ROSADO','1.2'),
('PAULO','1.8'),
('PROVEEDOR SOTELO','1.8'),
('RODRIGO CALDERON','3'),
('SALVADOR','4'),
('SANDRA KURI','4'),
('SUSANA','2.5'),
('SUSANA | SINDICATO','3'),
('TERESITA OROZCO','4'),
('URIEL','1.2')
*/